import pool from "./db.ts";

export async function getAllSessions(userId: number) {
  const result = await pool.query(
    `SELECT s.id, s.performed_on, s.notes, s.session_order,
            t.training_name, t.category,
            COALESCE(
              (SELECT json_agg(st ORDER BY st.set_order)
               FROM training_sets st
               WHERE st.session_id = s.id),
              '[]'::json
            ) AS sets
     FROM training_sessions s
     JOIN training_types t ON t.id = s.training_type_id
     WHERE s.user_id = $1
     ORDER BY s.performed_on DESC, s.session_order`,
    [userId],
  );

  return result.rows;
}

export type SetInput = {
  weight_kg?: number | null;
  reps?: number | null;
  duration_seconds?: number | null;
  distance_km?: number | null;
  avg_heart_rate_bpm?: number | null;
  avg_power_watts?: number | null;
  avg_cadence?: number | null;
};

export async function createSessionWithSets(
  userId: number,
  trainingTypeId: number,
  performedOn: string,
  notes: string | null,
  sets: SetInput[],
) {
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    // session_order is assigned here rather than sent by the caller: it is
    // always "next slot for this user on this day", so nothing upstream has
    // to know or validate it.
    // The CTE lets the insert join back to training_types, so this returns the
    // same shape as getAllSessions and the client needs only one Session type.
    const sessionResult = await client.query(
      `WITH inserted AS (
        INSERT INTO training_sessions
          (user_id, training_type_id, performed_on, notes, session_order)
        SELECT $1, t.id, $3, $4,
               COALESCE(
                 (SELECT MAX(s.session_order) + 1
                  FROM training_sessions s
                  WHERE s.user_id = $1 AND s.performed_on = $3),
                 1
               )
        FROM training_types t
        WHERE t.id = $2 AND t.user_id = $1
        RETURNING *
      )
      SELECT i.id, i.performed_on, i.notes, i.session_order,
             t.training_name, t.category
      FROM inserted i
      JOIN training_types t ON t.id = i.training_type_id`,
      [userId, trainingTypeId, performedOn, notes],
    );

    const session = sessionResult.rows[0];
    if (!session) {
      await client.query("ROLLBACK");
      return undefined;
    }

    const insertedSets = [];
    for (const [index, set] of sets.entries()) {
      const setResult = await client.query(
        `INSERT INTO training_sets
        (session_id, set_order, weight_kg, reps, duration_seconds, distance_km,
        avg_heart_rate_bpm, avg_power_watts, avg_cadence)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`,
        [
          session.id,
          index + 1,
          set.weight_kg ?? null,
          set.reps ?? null,
          set.duration_seconds ?? null,
          set.distance_km ?? null,
          set.avg_heart_rate_bpm ?? null,
          set.avg_power_watts ?? null,
          set.avg_cadence ?? null,
        ],
      );
      insertedSets.push(setResult.rows[0]);
    }

    await client.query("COMMIT");
    return { ...session, sets: insertedSets };
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

// The value columns of training_sets, in the order every set query binds them.
// avg_speed_kmh is generated by the database and never written.
const SET_VALUES = (set: SetInput) => [
  set.weight_kg ?? null,
  set.reps ?? null,
  set.duration_seconds ?? null,
  set.distance_km ?? null,
  set.avg_heart_rate_bpm ?? null,
  set.avg_power_watts ?? null,
  set.avg_cadence ?? null,
];

// Append one set to an existing session, as it is performed. set_order is the
// next free slot, mirroring how session_order works one level up.
// Returns undefined if the session isn't this user's: the SELECT yields no
// row, so nothing is inserted and ownership never needs a separate check.
export async function addSetToSession(
  sessionId: number,
  userId: number,
  set: SetInput,
) {
  const result = await pool.query(
    `INSERT INTO training_sets
       (session_id, set_order, weight_kg, reps, duration_seconds, distance_km,
        avg_heart_rate_bpm, avg_power_watts, avg_cadence)
     SELECT s.id,
            COALESCE(
              (SELECT MAX(st.set_order) + 1
               FROM training_sets st
               WHERE st.session_id = s.id),
              1
            ),
            $3, $4, $5, $6, $7, $8, $9
     FROM training_sessions s
     WHERE s.id = $1 AND s.user_id = $2
     RETURNING *`,
    [sessionId, userId, ...SET_VALUES(set)],
  );
  return result.rows[0];
}

// Replaces every value column, so an omitted field is cleared rather than
// left behind. The join to training_sessions is what enforces ownership.
export async function editSet(setId: number, userId: number, set: SetInput) {
  const result = await pool.query(
    `UPDATE training_sets st
     SET weight_kg = $3, reps = $4, duration_seconds = $5, distance_km = $6,
         avg_heart_rate_bpm = $7, avg_power_watts = $8, avg_cadence = $9
     FROM training_sessions s
     WHERE st.id = $1 AND st.session_id = s.id AND s.user_id = $2
     RETURNING st.*`,
    [setId, userId, ...SET_VALUES(set)],
  );
  return result.rows[0];
}

// Leaves a gap in set_order (1, 2, 4). Nothing depends on the numbers being
// contiguous — they only order the rows — and renumbering would fight the
// UNIQUE (session_id, set_order) constraint.
export async function deleteSet(setId: number, userId: number) {
  const result = await pool.query(
    `DELETE FROM training_sets st
     USING training_sessions s
     WHERE st.id = $1 AND st.session_id = s.id AND s.user_id = $2
     RETURNING st.id`,
    [setId, userId],
  );
  return result.rows[0];
}

// Renumbers a whole day at once: the caller sends every session it has on
// that date, in the order it wants them, and each id's position becomes its
// session_order. Returns false unless those ids are exactly that user's
// sessions for that day, so a stale or partial list can't half-renumber it
// and a foreign id can't be smuggled in.
export async function reorderSessions(
  userId: number,
  performedOn: string,
  sessionIds: number[],
) {
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    // Locked so a concurrent edit can't land between this check and the
    // renumber below.
    const existing = await client.query(
      `SELECT id FROM training_sessions
       WHERE user_id = $1 AND performed_on = $2
       FOR UPDATE`,
      [userId, performedOn],
    );

    const owned = new Set<number>(existing.rows.map((row) => row.id));
    const isWholeDay =
      owned.size === sessionIds.length &&
      sessionIds.every((id) => owned.has(id));

    if (!isWholeDay) {
      await client.query("ROLLBACK");
      return false;
    }

    // One statement rather than a loop: WITH ORDINALITY numbers the array,
    // and there is no UNIQUE constraint on (user_id, performed_on,
    // session_order) for the intermediate states to collide with.
    await client.query(
      `UPDATE training_sessions s
       SET session_order = new_order.ordinal
       FROM unnest($3::int[]) WITH ORDINALITY AS new_order(session_id, ordinal)
       WHERE s.id = new_order.session_id
         AND s.user_id = $1 AND s.performed_on = $2`,
      [userId, performedOn, sessionIds],
    );

    await client.query("COMMIT");
    return true;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function editSessionNotes(
  sessionId: number,
  userId: number,
  notes: string | null,
) {
  const result = await pool.query(
    `UPDATE training_sessions SET notes = $3
     WHERE id = $1 AND user_id = $2
     RETURNING *`,
    [sessionId, userId, notes],
  );
  return result.rows[0];
}

// Sets go with it via ON DELETE CASCADE
export async function deleteSession(sessionId: number, userId: number) {
  const result = await pool.query(
    `DELETE FROM training_sessions WHERE id = $1 AND user_id = $2 RETURNING id`,
    [sessionId, userId],
  );
  return result.rows[0];
}
